// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWE7AvSyuj0yxwp8xFWngCeulFEpiFrig',
    appId: '1:474703516179:android:81a3240431e4560f6fe5e6',
    messagingSenderId: '474703516179',
    projectId: 'inotedev-29330',
    storageBucket: 'inotedev-29330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwVIXD4cd5GscOBipdQ7cHNKWhAXYDWzA',
    appId: '1:474703516179:ios:6ff20e2401fa0f806fe5e6',
    messagingSenderId: '474703516179',
    projectId: 'inotedev-29330',
    storageBucket: 'inotedev-29330.firebasestorage.app',
    iosBundleId: 'store.inoteapp.inoteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwVIXD4cd5GscOBipdQ7cHNKWhAXYDWzA',
    appId: '1:474703516179:ios:6ff20e2401fa0f806fe5e6',
    messagingSenderId: '474703516179',
    projectId: 'inotedev-29330',
    storageBucket: 'inotedev-29330.firebasestorage.app',
    iosBundleId: 'store.inoteapp.inoteapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxy-tqvTchmZg6FkXGKPz9R5_cT3rQEwQ',
    appId: '1:85523872464:web:15447d4fb576a5077ebcd5',
    messagingSenderId: '85523872464',
    projectId: 'inotedev',
    authDomain: 'inotedev.firebaseapp.com',
    storageBucket: 'inotedev.firebasestorage.app',
    measurementId: 'G-KMQYMQBC7E',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxy-tqvTchmZg6FkXGKPz9R5_cT3rQEwQ',
    appId: '1:85523872464:web:ea7652443acfec417ebcd5',
    messagingSenderId: '85523872464',
    projectId: 'inotedev',
    authDomain: 'inotedev.firebaseapp.com',
    storageBucket: 'inotedev.firebasestorage.app',
    measurementId: 'G-RJQPTJJPEM',
  );

}